Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(run.py:1): Gdk-CRITICAL **: 11:11:08.746: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
