Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(run.py:1): Gdk-CRITICAL **: 16:56:29.258: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
mv: cannot stat '*.csv': No such file or directory
mv: cannot stat '*.png': No such file or directory
mv: 'summary.txt' and '/home/filippo/files/./summary.txt' are the same file
